 
name: Latest Changes

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # To allow latest-changes to commit to master
          token: ${{ secrets.TOKEN_GITHUB }}
      - uses: docker://fabiom1991/meinhelg-gunicorn-docker
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
